classpath=.
changeLogFile=liquibase/changelog/db.changelog-master.xml
url=jdbc:sqlserver://localhost:1433;databaseName=LocalEatsDB
username=sa
password=YourStrongPassword123
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
